Add evolutionary conservation eval pipeline v1-beta (#11)
* Add simple pipeline example to docs

* Delete unnecessary examples

* Fix logging and serialize step data as json

* Implement Xarray writes

* Synchronize HF writes

* Refactor HF path management

* Refactor HF I/O

* Infer worker count from available GPUs

* Add fabfile, detach on ray init, update docs

* Switch to SkyPilot fork with Lambda instance launch patch

* Switch back to head node inference in tasks

* Clean up HF examples, fix README typos

* Fix README typos

* Add comment on ordering of nodes in SkyPilot env vars

* Use python for json parse instead of sed on cluster setup

diff --git a/src/pipelines/plantcad2/evaluation/configs/task.sky.yaml b/src/pipelines/plantcad2/evaluation/configs/task.sky.yaml
--- a/src/pipelines/plantcad2/evaluation/configs/task.sky.yaml
+++ b/src/pipelines/plantcad2/evaluation/configs/task.sky.yaml
@@ -1,8 +1,18 @@
 name: plantcad2-evaluation
 
-num_nodes: 2
+# IMPORTANT: Do not set `num_nodes` for task configuration.
+# All nodes must be used to execute each task and the size of the cluster will vary,
+# so each task invocation must include --num-nodes N.  All nodes must be included b/c:
+# - The Ray cluster used by Thalas needs to have the Sky workdir synced to every node
+# - `SKYPILOT_NODE_IPS` will not necessarily include the head node when using a node subset
+# - Thalas introspects on the Ray cluster through the `localhost`, i.e. it assumes execution on the head node
+# num_nodes: N
+
 envs:
+  # SkyPilot will enforce the existence of any env vars with `null` values here
   HUGGING_FACE_HUB_TOKEN: null
+  RAY_GCS_PORT: 6479
+  RAY_DEDUP_LOGS: 1
   ARGS: ""
 
 workdir: .
@@ -16,19 +26,38 @@ run: |
   echo "SKYPILOT_NODE_IPS: $SKYPILOT_NODE_IPS"
   echo "SKYPILOT_NODE_RANK: $SKYPILOT_NODE_RANK"
 
-  # Execute the pipeline in a fresh environment with allowlist to
-  # avoid collisions between SkyPilot Ray and Thalas Ray clusters
-  env -i \
-    HUGGING_FACE_HUB_TOKEN="$HUGGING_FACE_HUB_TOKEN" \
-    SKYPILOT_NODE_IPS="$SKYPILOT_NODE_IPS" \
-    SKYPILOT_NODE_RANK="$SKYPILOT_NODE_RANK" \
-    SKYPILOT_NUM_NODES="$SKYPILOT_NUM_NODES" \
-    SKYPILOT_NUM_GPUS_PER_NODE="$SKYPILOT_NUM_GPUS_PER_NODE" \
-    bash --login scripts/ray_run.sh \
-    python -m src.pipelines.plantcad2.evaluation.pipeline \
-      --config_path src/pipelines/plantcad2/evaluation/configs/config.yaml \
-      --tasks.evolutionary_constraint.generate_logits.simulation_mode false \
-      --tasks.evolutionary_constraint.generate_logits.num_workers 2 \
-      --executor.prefix hf://datasets/plantcad/_dev_pc2_eval \
-      --executor.force_run_failed true \
-      ${ARGS}
+  # Log Ray environment variables
+  echo "RAY_GCS_PORT: $RAY_GCS_PORT"
+  echo "RAY_DEDUP_LOGS: $RAY_DEDUP_LOGS"
+
+  # Run on rank 0 only as defense against accidental multi-node task execution;
+  # the first node chosen for a task by SkyPilot always has rank 0 (which may be a worker)
+  if [ "$SKYPILOT_NODE_RANK" == "0" ]; then
+
+    # Infer head node IP
+    # Note that `SKYPILOT_NODE_IPS` is ordered by node rank; see:
+    # https://docs.skypilot.co/en/latest/running-jobs/environment-variables.html#environment-variables-for-run
+    RAY_HEAD_NODE_IP=$(echo "$SKYPILOT_NODE_IPS" | head -n1)
+    if [ -z "$RAY_HEAD_NODE_IP" ]; then
+      echo "ERROR: RAY_HEAD_NODE_IP is not set" >&2
+      exit 1
+    fi
+
+    # Avoid RAY_ADDRESS in parent env to avoid clobbering SkyPilot's RAY_ADDRESS
+    RAY_GCS_ADDRESS="$RAY_HEAD_NODE_IP:$RAY_GCS_PORT"
+
+    echo "RAY_GCS_ADDRESS: $RAY_GCS_ADDRESS"
+
+    # Execute the pipeline in sanitized environment
+    env -i \
+      HOME="$HOME" \
+      RAY_DEDUP_LOGS="$RAY_DEDUP_LOGS" \
+      RAY_ADDRESS="$RAY_GCS_ADDRESS" \
+      HUGGING_FACE_HUB_TOKEN="$HUGGING_FACE_HUB_TOKEN" \
+      bash -c "source .venv/bin/activate && python -m src.pipelines.plantcad2.evaluation.pipeline \
+        --config_path src/pipelines/plantcad2/evaluation/configs/config.yaml \
+        --tasks.evolutionary_constraint.generate_logits.simulation_mode false \
+        --executor.prefix hf://datasets/plantcad/_dev_pc2_eval \
+        --executor.force_run_failed true \
+        ${ARGS}"
+  fi
